### ISSUE TITLE
dvembed sends message with a single frame video

### ISSUE THREAD

**Issue by kepler471** [kepler471/dvembed#5]
Sometimes a link which just has an image, will be processed as if there is a video, and so the bot will send that image, converted to mp4, as a video which seems to just have one frame.

**Comment by kepler471** [comment]
@mija you said you came accross this issue a few times, if you are able to, can you send the specific links that trigger this? It would be really helpful for testing 🤓

**Comment by mija** [comment]
https://old.reddit.com/r/StarWars/comments/l1l7f6/finished_this_last_night_took_me_30_hours_to/

there's one example it happened with.
Here's the bots response:
https://cdn.discordapp.com/attachments/211609129284796418/801929818831716372/finished_this_last_night_took_me_30_hours_to.mp4

**Comment by mija** [comment]
Any progress on this project my dude? Its a good project.

**Comment by kepler471** [comment]
Yes! Should have an update today :)

**Comment by kepler471** [comment]
@mija Hey, will close this issue, this seems to be working properly.

I think I also have a good plan now for large files which I will get working on next!! See #7 , which I think will lead to reducing the work of `youtube-dl`, and we can keep it in as a weak requirement for much larger files.

So currently, to get the bot running:
- get the latest code, put the token into `token.go`
- have youtube-dl installed. I think the best suggestion for you on Windows will be to get Python installed and added to path, then `pip3 install youtube-dl`. The alternative would be to install the standalone `youtube-dl.exe` and then change `download.go: line 24` to include the `.exe`.
- `ffmpeg` is still not being used so wont need to worry about that. 

Let me know about any issues, I think getting `youtube-dl` installed as a python package, should fix your other problem with the paths and directories, as long as python is properly on the path!

✌️
